let bert_url = 'http://localhost:5000';

function parseText(text) {
    let doc = nlp(text);
    let sentences = doc.json();
    let words = sentences.map(sentence => sentence.terms.map(term => term.text)).flat()
    return words;
}

function taggedText(text, tag) {
    let doc = nlp(text);
    let match = doc.match(tag).out('array');
    return match;
}

function callBERT(leftwords, rightwords, badwords) {
    return fetch(base_url + '/bert', {
        method: 'POST',
        headers: {
        'Content-Type': 'application/json',
        },
        body: JSON.stringify({
            leftwords: leftwords,
            rightwords: rightwords,
            badwords: badwords,
        }),
        mode: 'cors'
    }).then(response => {
        return response.json()
    })
    .then(word => {
        word = word.toUpperCase();
        word = word.replace("##", "") // Eventually we may want to concat these
        return word;
    })
}

class Worder {
    constructor() {
        this.words = {}; // {id: {word: "word", x: 0, y: 0, size: 0, wordWidth: 0}}
        this.wordOrder = []; // [id, id, id]
        this._nextWordID = 0;
    }
    
    /* 
    * This function is for the Worder mixin to implement. It should take a note and return a word.
    */
    _noteToWordProtocol(note) {
        return note.ToString();
    }

    addWordToContext(word) {
        this.words[word.id] = word;
        if (word.after) {
            console.log("Adding word after", word);
            let index = this.wordOrder.indexOf(word.after);
            console.log("Index of after word", index);
            if (index === -1) {
                this.wordOrder.unshift(word.id);
            } else {
                this.wordOrder.splice(index + 1, 0, word.id);
            }
            delete word.after;
        } else {
            this.wordOrder.push(word.id);
        }
    }

    updateContext(newContext) {
        this.words = {}
        this.wordOrder = [];

        let tokenized;
        if (typeof newContext === 'string') {
            tokenized = parseText(newContext);
        } else {
            tokenized = newContext;
        }
        
        for(let word of tokenized) {
            this.addWordToContext(this.formatWord(word));
        }
    }

    getContextData() {
        return this.wordOrder.map(id => this.words[id]);
    }
 
    getContext() {
        return this.wordOrder.map(id => this.words[id].word);
    }

    formatWord(word) {
        return {
            id: this.nextID(),
            word: word,
        }
    }

    noteToWord(note) {
        let word = this._noteToWordProtocol(note)
        return this.formatWord(word);
    }

    nextID() {
        return this._nextWordID++;
    }
}

let indexWorderMixin = {
    setCorpus(corpus) {
        this.corpus = parseText(corpus);
    },

    noteToWordByIndex(note) {
        this.lastWord = this.corpus[note % this.corpus.length];
        return this.lastWord;
    },

    _noteToWordProtocol(note) {
        return this.noteToWordByIndex(note);
    }
}

let bertWorderMixin = {
    noteToWordByBert(note) {
        let leftwords = this.getContext().slice(-5);
        let rightwords = [];
        let badwords = [];
        
        return callBERT(leftwords, rightwords, badwords).then(word => {
            return word;
        });
    },

    _noteToWordProtocol(note) {
        return this.noteToWordByBert(note);
    }
}

let llamaWorderMixin = {
    noteToWordByLlama(note) {
        let context = this.getContext().join(' ');
        prompt = "<This a dadaist poem. Generated by AI and love.>\n\n" + context
        return fetch('http://localhost:11434/api/generate', {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
            },
            body: JSON.stringify({
                model: "llama2:7b-text",
                prompt: prompt,
                options: {
                    num_predict: 5,
                    num_ctx: 300
                }
            }),
            mode: 'cors'
        }).then(response => {
            return response.text();
        }).then(text => {
            const jsonLines = text.trim().split('\n'); // Split the text by newlines
            const jsonData = jsonLines.map(line => JSON.parse(line)); // Parse each line as JSON
            console.log(jsonData)
            let words = jsonData.map(data => data['response'].toUpperCase())
            let lastSpace = words.length;
            for (let i = 0; i < words.length; i++) {
                let word = words[i];
                if (word != '' && word[0] == ' ') {
                    lastSpace = i;
                }
            }
            words.splice(lastSpace, words.length - lastSpace);
            words = words.join('');
            const parsed = parseText(words);
            const final = parsed.map(this.formatWord.bind(this))
            console.log("Ollama", parsed, "context", context);

            return final;
          })
    },

    _noteToWordProtocol(note) {
        return this.noteToWordByLlama(note);
    }
}